---
title: "Descriptive and regression tables with {gtsummary}"
execute: 
  eval: false
---

# Overview

`{gtsummary}` has become my preferred way of creating tables of all types. It's highly customizable and can almost always get the exact output I'm looking for. It's based of the `{gt}` package for creating tables, so can be even more customizable. It also includes functions for pulling out numbers from the tables to report in the text.

# Slides

Open the slides in a new tab [here](../slides/gtsummary.html){target="_blank"}.

Download the slides as a new pdf [here](../slides/gtsummary.pdf){target="_blank"}.


<div>
```{=html}
<iframe class="slide-deck" src="../slides/gtsummary.html"></iframe>
```
</div>

# Exercises

1. Download the quarto document [here](../slides/_gtsummary_examples.qmd) and put it into your R project folder.
2. Render the document.
3. Make a `tbl_summary()`. Include (at least) number of hours of sleep on weekdays and weekends, categorical region, and income and make sure they are nicely labeled. Play around with the extra functions from the examples and/or from the [documentation](https://www.danieldsjoberg.com/gtsummary/)
4. Fit a Poisson regression for the number of siblings, using at least 3 predictors of your choice. Create a nice table displaying your Poisson regression and its exponentiated coefficients.

# Resources

- [`{gtsummary}` documentation](https://www.danieldsjoberg.com/gtsummary/)
- [`{gt}` documentation](https://gt.rstudio.com/)
- [`{flextable}` documentation](https://ardata-fr.github.io/flextable-book/)
- [`{gtExtras}` documentation](https://jthomasmock.github.io/gtExtras/)
- Discussion [here](https://github.com/quarto-dev/quarto-cli/issues/1556) and [here](https://github.com/davidgohel/flextable/issues/494) about table rendering issues that will be fixed in the next quarto update.
